const ONE_SECOND_IN_MILLISECONDS = 1000;
const ONE_MINUTE_IN_SECONDS = 60;
const ONE_HOUR_IN_SECONDS = 60 * 60;
const ONE_DAY_IN_SECONDS = 24 * ONE_HOUR_IN_SECONDS;
const ONE_WEEK_IN_SECONDS = 7 * ONE_DAY_IN_SECONDS;
const ONE_MONTH_IN_SECONDS = 30 * ONE_DAY_IN_SECONDS;

const ONE_MINUTE_IN_MILLISECONDS = ONE_MINUTE_IN_SECONDS * ONE_SECOND_IN_MILLISECONDS;
const ONE_HOUR_IN_MILLISECONDS = ONE_HOUR_IN_SECONDS * ONE_SECOND_IN_MILLISECONDS;
const ONE_DAY_IN_MILLISECONDS = ONE_DAY_IN_SECONDS * ONE_SECOND_IN_MILLISECONDS;
const ONE_WEEK_IN_MILLISECONDS = ONE_WEEK_IN_SECONDS * ONE_SECOND_IN_MILLISECONDS;
const ONE_MONTH_IN_MILLISECONDS = ONE_MONTH_IN_SECONDS * ONE_SECOND_IN_MILLISECONDS;

export {
    ONE_SECOND_IN_MILLISECONDS,
    ONE_MINUTE_IN_SECONDS,
    ONE_HOUR_IN_SECONDS,
    ONE_DAY_IN_SECONDS,
    ONE_WEEK_IN_SECONDS,
    ONE_MONTH_IN_SECONDS,
    ONE_MINUTE_IN_MILLISECONDS,
    ONE_HOUR_IN_MILLISECONDS,
    ONE_DAY_IN_MILLISECONDS,
    ONE_WEEK_IN_MILLISECONDS,
    ONE_MONTH_IN_MILLISECONDS,
};
